# Generated by Django 6.0.6 on 2026-08-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.CharField(max_length=150)),
                ('reaction', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=20)),
                ('noted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patientprofile')),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'ordering': ['-severity', 'allergen'],
                'indexes': [models.Index(fields=['patient'], name='medical_rec_patient_16738f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('record_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('treatment_plan', 'Treatment Plan'), ('progress_note', 'Progress Note'), ('discharge_summary', 'Discharge Summary'), ('lab_summary', 'Lab Summary')], default='progress_note', max_length=20)),
                ('visit_date', models.DateField()),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('icd_code', models.CharField(blank=True, help_text='Optional ICD-10 diagnosis code', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='emr_attachments/%Y/%m/')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-visit_date'], name='medical_rec_patient_89342e_idx'), models.Index(fields=['record_type'], name='medical_rec_record__be12f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='bpm', null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, help_text='mmHg', null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, help_text='SpO2 %', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patientprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='medical_rec_patient_6bb49f_idx')],
            },
        ),
    ]
