# Generated by Django 6.0.6 on 2026-08-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nurse_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('department', models.CharField(default='General', max_length=100)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], default='morning', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('assigned_ward', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department'], name='nurses_nurs_departm_af5dc8_idx'), models.Index(fields=['shift'], name='nurses_nurs_shift_295e87_idx')],
            },
        ),
    ]
