# Generated by Django 6.0.6 on 2026-08-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lab_results/%Y/%m/')),
                ('is_reviewed_by_doctor', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResultParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_range_low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('reference_range_high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='labs.labresult')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('test_type', models.CharField(choices=[('cbc', 'Complete Blood Count (CBC)'), ('blood_glucose', 'Blood Glucose'), ('lipid_panel', 'Lipid Panel'), ('liver_function', 'Liver Function Panel'), ('kidney_function', 'Kidney Function Panel'), ('thyroid_panel', 'Thyroid Panel'), ('electrolytes', 'Electrolyte Panel'), ('urinalysis', 'Urinalysis'), ('coagulation', 'Coagulation Panel'), ('culture_sensitivity', 'Culture & Sensitivity'), ('xray', 'X-Ray Imaging'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('covid_pcr', 'COVID-19 PCR'), ('other', 'Other')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immediate)')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, help_text='Reason for test / clinical context')),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patientprofile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='test_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='labs.labtestrequest'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['status'], name='labs_labtes_status_000026_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['priority'], name='labs_labtes_priorit_bc0fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['patient', '-created_at'], name='labs_labtes_patient_dcdc8c_idx'),
        ),
    ]
