# Generated by Django 6.0.6 on 2026-08-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('analgesic', 'Analgesic'), ('antibiotic', 'Antibiotic'), ('antiviral', 'Antiviral'), ('cardiovascular', 'Cardiovascular'), ('respiratory', 'Respiratory'), ('gastrointestinal', 'Gastrointestinal'), ('endocrine', 'Endocrine'), ('neurological', 'Neurological'), ('vitamin_supplement', 'Vitamin / Supplement'), ('other', 'Other')], default='other', max_length=30)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500mg', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='pharmacy_me_name_aa3c4f_idx'), models.Index(fields=['category'], name='pharmacy_me_categor_6b0964_idx'), models.Index(fields=['stock_quantity'], name='pharmacy_me_stock_q_37693e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('restock', 'Restock'), ('dispense', 'Dispense'), ('adjustment', 'Manual Adjustment'), ('return', 'Return'), ('expired', 'Expired / Written Off')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('resulting_quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pharmacy.medicine')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medicine', '-created_at'], name='pharmacy_st_medicin_cc8ea4_idx')],
            },
        ),
    ]
