# Generated by Django 6.0.6 on 2026-08-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('specialization', models.CharField(default='General Medicine', max_length=150)),
                ('department', models.CharField(default='General', max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.CharField(blank=True, max_length=255)),
                ('is_available_for_booking', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='doctors.doctorprofile')),
            ],
            options={
                'verbose_name_plural': 'Doctor availability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('on_call', 'On-call')], default='morning', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['department'], name='doctors_doc_departm_f1ea26_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialization'], name='doctors_doc_special_a5690e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailability',
            index=models.Index(fields=['doctor', 'weekday'], name='doctors_doc_doctor__a521b8_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorshift',
            index=models.Index(fields=['doctor', 'date'], name='doctors_doc_doctor__ad1a40_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorshift',
            index=models.Index(fields=['date'], name='doctors_doc_date_66ffb1_idx'),
        ),
    ]
